// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"errors"
	"fmt"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"strings"
	"sync"
)

// SseServer is a fake server for instances of the ssegroup.SseClient type.
type SseServer struct {
	// SseNamedServer contains the fakes for client SseNamedClient
	SseNamedServer SseNamedServer

	// SseProtocolServer contains the fakes for client SseProtocolClient
	SseProtocolServer SseProtocolServer

	// SseRetrieveServer contains the fakes for client SseRetrieveClient
	SseRetrieveServer SseRetrieveServer

	// SseUnnamedServer contains the fakes for client SseUnnamedClient
	SseUnnamedServer SseUnnamedServer
}

// NewSseServerTransport creates a new instance of SseServerTransport with the provided implementation.
// The returned SseServerTransport instance is connected to an instance of ssegroup.SseClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseServerTransport(srv *SseServer) *SseServerTransport {
	return &SseServerTransport{srv: srv}
}

// SseServerTransport connects instances of ssegroup.SseClient to instances of SseServer.
// Don't use this type directly, use NewSseServerTransport instead.
type SseServerTransport struct {
	srv                 *SseServer
	trMu                sync.Mutex
	trSseNamedServer    *SseNamedServerTransport
	trSseProtocolServer *SseProtocolServerTransport
	trSseRetrieveServer *SseRetrieveServerTransport
	trSseUnnamedServer  *SseUnnamedServerTransport
}

// Do implements the policy.Transporter interface for SseServerTransport.
func (s *SseServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return s.dispatchToClientFake(req, method[:strings.Index(method, ".")])
}

func (s *SseServerTransport) dispatchToClientFake(req *http.Request, client string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch client {
	case "SseNamedClient":
		initServer(&s.trMu, &s.trSseNamedServer, func() *SseNamedServerTransport {
			return NewSseNamedServerTransport(&s.srv.SseNamedServer)
		})
		resp, err = s.trSseNamedServer.Do(req)
	case "SseProtocolClient", "SseProtocolDataClient":
		initServer(&s.trMu, &s.trSseProtocolServer, func() *SseProtocolServerTransport {
			return NewSseProtocolServerTransport(&s.srv.SseProtocolServer)
		})
		resp, err = s.trSseProtocolServer.Do(req)
	case "SseRetrieveClient":
		initServer(&s.trMu, &s.trSseRetrieveServer, func() *SseRetrieveServerTransport {
			return NewSseRetrieveServerTransport(&s.srv.SseRetrieveServer)
		})
		resp, err = s.trSseRetrieveServer.Do(req)
	case "SseUnnamedClient":
		initServer(&s.trMu, &s.trSseUnnamedServer, func() *SseUnnamedServerTransport {
			return NewSseUnnamedServerTransport(&s.srv.SseUnnamedServer)
		})
		resp, err = s.trSseUnnamedServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	return resp, err
}

// set this to conditionally intercept incoming requests to SseServerTransport
var sseServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
