// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"ssegroup"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseRetrieveServer is a fake server for instances of the ssegroup.SseRetrieveClient type.
type SseRetrieveServer struct {
	// Stream is the fake for method SseRetrieveClient.Stream
	// HTTP status codes to indicate success: http.StatusOK
	Stream func(ctx context.Context, request ssegroup.RetrievalRequest, options *ssegroup.SseRetrieveClientStreamOptions) (resp azfake.SSEResponder[ssegroup.RetrievalEvents], errResp azfake.ErrorResponder)
}

// NewSseRetrieveServerTransport creates a new instance of SseRetrieveServerTransport with the provided implementation.
// The returned SseRetrieveServerTransport instance is connected to an instance of ssegroup.SseRetrieveClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseRetrieveServerTransport(srv *SseRetrieveServer) *SseRetrieveServerTransport {
	return &SseRetrieveServerTransport{srv: srv}
}

// SseRetrieveServerTransport connects instances of ssegroup.SseRetrieveClient to instances of SseRetrieveServer.
// Don't use this type directly, use NewSseRetrieveServerTransport instead.
type SseRetrieveServerTransport struct {
	srv *SseRetrieveServer
}

// Do implements the policy.Transporter interface for SseRetrieveServerTransport.
func (s *SseRetrieveServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return s.dispatchToMethodFake(req, method)
}

func (s *SseRetrieveServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sseRetrieveServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sseRetrieveServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SseRetrieveClient.Stream":
				res.resp, res.err = s.dispatchStream(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SseRetrieveServerTransport) dispatchStream(req *http.Request) (*http.Response, error) {
	if s.srv.Stream == nil {
		return nil, &nonRetriableError{errors.New("fake for method Stream not implemented")}
	}
	body, err := server.UnmarshalRequestAsJSON[ssegroup.RetrievalRequest](req)
	if err != nil {
		return nil, err
	}
	respr, errRespr := s.srv.Stream(req.Context(), body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	streamBody, err := server.MarshalSSEResponder(&respr, encodeRetrievalEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        streamBody,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SseRetrieveServerTransport
var sseRetrieveServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
