// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"ssegroup"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseProtocolDataServer is a fake server for instances of the ssegroup.SseProtocolDataClient type.
type SseProtocolDataServer struct {
	// WithEnvelope is the fake for method SseProtocolDataClient.WithEnvelope
	// HTTP status codes to indicate success: http.StatusOK
	WithEnvelope func(ctx context.Context, options *ssegroup.SseProtocolDataClientWithEnvelopeOptions) (resp azfake.SSEResponder[ssegroup.DataEvents], errResp azfake.ErrorResponder)

	// WithoutEnvelope is the fake for method SseProtocolDataClient.WithoutEnvelope
	// HTTP status codes to indicate success: http.StatusOK
	WithoutEnvelope func(ctx context.Context, options *ssegroup.SseProtocolDataClientWithoutEnvelopeOptions) (resp azfake.SSEResponder[ssegroup.DataEvents], errResp azfake.ErrorResponder)
}

// NewSseProtocolDataServerTransport creates a new instance of SseProtocolDataServerTransport with the provided implementation.
// The returned SseProtocolDataServerTransport instance is connected to an instance of ssegroup.SseProtocolDataClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseProtocolDataServerTransport(srv *SseProtocolDataServer) *SseProtocolDataServerTransport {
	return &SseProtocolDataServerTransport{srv: srv}
}

// SseProtocolDataServerTransport connects instances of ssegroup.SseProtocolDataClient to instances of SseProtocolDataServer.
// Don't use this type directly, use NewSseProtocolDataServerTransport instead.
type SseProtocolDataServerTransport struct {
	srv *SseProtocolDataServer
}

// Do implements the policy.Transporter interface for SseProtocolDataServerTransport.
func (s *SseProtocolDataServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return s.dispatchToMethodFake(req, method)
}

func (s *SseProtocolDataServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sseProtocolDataServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sseProtocolDataServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SseProtocolDataClient.WithEnvelope":
				res.resp, res.err = s.dispatchWithEnvelope(req)
			case "SseProtocolDataClient.WithoutEnvelope":
				res.resp, res.err = s.dispatchWithoutEnvelope(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SseProtocolDataServerTransport) dispatchWithEnvelope(req *http.Request) (*http.Response, error) {
	if s.srv.WithEnvelope == nil {
		return nil, &nonRetriableError{errors.New("fake for method WithEnvelope not implemented")}
	}
	respr, errRespr := s.srv.WithEnvelope(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeDataEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolDataServerTransport) dispatchWithoutEnvelope(req *http.Request) (*http.Response, error) {
	if s.srv.WithoutEnvelope == nil {
		return nil, &nonRetriableError{errors.New("fake for method WithoutEnvelope not implemented")}
	}
	respr, errRespr := s.srv.WithoutEnvelope(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeDataEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SseProtocolDataServerTransport
var sseProtocolDataServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
