// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"ssegroup"
	"ssegroup/streaming"
	"strings"
	"sync"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseProtocolServer is a fake server for instances of the ssegroup.SseProtocolClient type.
type SseProtocolServer struct {
	// SseProtocolDataServer contains the fakes for client SseProtocolDataClient
	SseProtocolDataServer SseProtocolDataServer

	// ID is the fake for method SseProtocolClient.ID
	// HTTP status codes to indicate success: http.StatusOK
	ID func(ctx context.Context, options *ssegroup.SseProtocolClientIDOptions) (resp azfake.Responder[ssegroup.SseProtocolClientIDResponse], errResp azfake.ErrorResponder)

	// InvalidID is the fake for method SseProtocolClient.InvalidID
	// HTTP status codes to indicate success: http.StatusOK
	InvalidID func(ctx context.Context, options *ssegroup.SseProtocolClientInvalidIDOptions) (resp azfake.Responder[ssegroup.SseProtocolClientInvalidIDResponse], errResp azfake.ErrorResponder)

	// InvalidRetry is the fake for method SseProtocolClient.InvalidRetry
	// HTTP status codes to indicate success: http.StatusOK
	InvalidRetry func(ctx context.Context, options *ssegroup.SseProtocolClientInvalidRetryOptions) (resp azfake.Responder[ssegroup.SseProtocolClientInvalidRetryResponse], errResp azfake.ErrorResponder)

	// Reconnect is the fake for method SseProtocolClient.Reconnect
	// HTTP status codes to indicate success: http.StatusOK
	Reconnect func(ctx context.Context, options *ssegroup.SseProtocolClientReconnectOptions) (resp azfake.Responder[ssegroup.SseProtocolClientReconnectResponse], errResp azfake.ErrorResponder)

	// Retry is the fake for method SseProtocolClient.Retry
	// HTTP status codes to indicate success: http.StatusOK
	Retry func(ctx context.Context, options *ssegroup.SseProtocolClientRetryOptions) (resp azfake.Responder[ssegroup.SseProtocolClientRetryResponse], errResp azfake.ErrorResponder)
}

// NewSseProtocolServerTransport creates a new instance of SseProtocolServerTransport with the provided implementation.
// The returned SseProtocolServerTransport instance is connected to an instance of ssegroup.SseProtocolClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseProtocolServerTransport(srv *SseProtocolServer) *SseProtocolServerTransport {
	return &SseProtocolServerTransport{srv: srv}
}

// SseProtocolServerTransport connects instances of ssegroup.SseProtocolClient to instances of SseProtocolServer.
// Don't use this type directly, use NewSseProtocolServerTransport instead.
type SseProtocolServerTransport struct {
	srv                     *SseProtocolServer
	trMu                    sync.Mutex
	trSseProtocolDataServer *SseProtocolDataServerTransport
}

// Do implements the policy.Transporter interface for SseProtocolServerTransport.
func (s *SseProtocolServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	if client := method[:strings.Index(method, ".")]; client != "SseProtocolClient" {
		return s.dispatchToClientFake(req, client)
	}
	return s.dispatchToMethodFake(req, method)
}

func (s *SseProtocolServerTransport) dispatchToClientFake(req *http.Request, client string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch client {
	case "SseProtocolDataClient":
		initServer(&s.trMu, &s.trSseProtocolDataServer, func() *SseProtocolDataServerTransport {
			return NewSseProtocolDataServerTransport(&s.srv.SseProtocolDataServer)
		})
		resp, err = s.trSseProtocolDataServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	return resp, err
}

func (s *SseProtocolServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sseProtocolServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sseProtocolServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SseProtocolClient.ID":
				res.resp, res.err = s.dispatchID(req)
			case "SseProtocolClient.InvalidID":
				res.resp, res.err = s.dispatchInvalidID(req)
			case "SseProtocolClient.InvalidRetry":
				res.resp, res.err = s.dispatchInvalidRetry(req)
			case "SseProtocolClient.Reconnect":
				res.resp, res.err = s.dispatchReconnect(req)
			case "SseProtocolClient.Retry":
				res.resp, res.err = s.dispatchRetry(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SseProtocolServerTransport) dispatchID(req *http.Request) (*http.Response, error) {
	if s.srv.ID == nil {
		return nil, &nonRetriableError{errors.New("fake for method ID not implemented")}
	}
	respr, errRespr := s.srv.ID(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchInvalidID(req *http.Request) (*http.Response, error) {
	if s.srv.InvalidID == nil {
		return nil, &nonRetriableError{errors.New("fake for method InvalidID not implemented")}
	}
	respr, errRespr := s.srv.InvalidID(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchInvalidRetry(req *http.Request) (*http.Response, error) {
	if s.srv.InvalidRetry == nil {
		return nil, &nonRetriableError{errors.New("fake for method InvalidRetry not implemented")}
	}
	respr, errRespr := s.srv.InvalidRetry(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchReconnect(req *http.Request) (*http.Response, error) {
	if s.srv.Reconnect == nil {
		return nil, &nonRetriableError{errors.New("fake for method Reconnect not implemented")}
	}
	respr, errRespr := s.srv.Reconnect(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchRetry(req *http.Request) (*http.Response, error) {
	if s.srv.Retry == nil {
		return nil, &nonRetriableError{errors.New("fake for method Retry not implemented")}
	}
	respr, errRespr := s.srv.Retry(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SseProtocolServerTransport
var sseProtocolServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
