// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"slices"
	"ssegroup"
	"ssegroup/streaming"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseNamedServer is a fake server for instances of the ssegroup.SseNamedClient type.
type SseNamedServer struct {
	// Receive is the fake for method SseNamedClient.Receive
	// HTTP status codes to indicate success: http.StatusOK
	Receive func(ctx context.Context, options *ssegroup.SseNamedClientReceiveOptions) (resp azfake.Responder[ssegroup.SseNamedClientReceiveResponse], errResp azfake.ErrorResponder)
}

// NewSseNamedServerTransport creates a new instance of SseNamedServerTransport with the provided implementation.
// The returned SseNamedServerTransport instance is connected to an instance of ssegroup.SseNamedClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseNamedServerTransport(srv *SseNamedServer) *SseNamedServerTransport {
	return &SseNamedServerTransport{srv: srv}
}

// SseNamedServerTransport connects instances of ssegroup.SseNamedClient to instances of SseNamedServer.
// Don't use this type directly, use NewSseNamedServerTransport instead.
type SseNamedServerTransport struct {
	srv *SseNamedServer
}

// Do implements the policy.Transporter interface for SseNamedServerTransport.
func (s *SseNamedServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	return s.dispatchToMethodFake(req, method)
}

func (s *SseNamedServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sseNamedServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sseNamedServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SseNamedClient.Receive":
				res.resp, res.err = s.dispatchReceive(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SseNamedServerTransport) dispatchReceive(req *http.Request) (*http.Response, error) {
	if s.srv.Receive == nil {
		return nil, &nonRetriableError{errors.New("fake for method Receive not implemented")}
	}
	respr, errRespr := s.srv.Receive(req.Context(), nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !slices.Contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	body, err := streaming.MarshalEvent(server.GetResponse(respr).Stream)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(respContent, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SseNamedServerTransport
var sseNamedServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
