// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"encoding/json"
	"fmt"
	"ssegroup"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// encodeDataEvents renders a DataEvents value to an SSE frame.
func encodeDataEvents(e ssegroup.DataEvents) (streaming.EventFrame, error) {
	switch {
	case e.WithEnvelope != nil:
		var contents string
		if e.WithEnvelope.Contents != nil {
			contents = *e.WithEnvelope.Contents
		}
		return streaming.EventFrame{Type: "withEnvelope", Data: []byte(contents)}, nil
	case e.WithEnvelope1 != nil:
		data, err := json.Marshal(e.WithEnvelope1)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "withoutEnvelope", Data: data}, nil
	default:
		return streaming.EventFrame{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeProtocolEvents renders a ProtocolEvents value to an SSE frame.
func encodeProtocolEvents(e ssegroup.ProtocolEvents) (streaming.EventFrame, error) {
	if e.ProtocolInfo != nil {
		data, err := json.Marshal(e.ProtocolInfo)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "message", Data: data}, nil
	}
	return streaming.EventFrame{}, fmt.Errorf("no field set in %T", e)
}

// encodeResponseEvents renders a ResponseEvents value to an SSE frame.
func encodeResponseEvents(e ssegroup.ResponseEvents) (streaming.EventFrame, error) {
	switch {
	case e.ResponseCreated != nil:
		data, err := json.Marshal(e.ResponseCreated)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "responseCreated", Data: data}, nil
	case e.ResponseDelta != nil:
		data, err := json.Marshal(e.ResponseDelta)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "responseDelta", Data: data}, nil
	case e.LiteralString != nil:
		return streaming.EventFrame{Data: []byte(*e.LiteralString)}, nil
	default:
		return streaming.EventFrame{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeRetrievalEvents renders a RetrievalEvents value to an SSE frame.
func encodeRetrievalEvents(e ssegroup.RetrievalEvents) (streaming.EventFrame, error) {
	switch {
	case e.PartialResult != nil:
		data, err := json.Marshal(e.PartialResult)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "partialResult", Data: data}, nil
	case e.FinalResult != nil:
		data, err := json.Marshal(e.FinalResult)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Type: "finalResult", Data: data}, nil
	case e.LiteralString != nil:
		return streaming.EventFrame{Data: []byte(*e.LiteralString)}, nil
	default:
		return streaming.EventFrame{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeUnnamedEvents renders an UnnamedEvents value to an SSE frame.
func encodeUnnamedEvents(e ssegroup.UnnamedEvents) (streaming.EventFrame, error) {
	if e.Info != nil {
		data, err := json.Marshal(e.Info)
		if err != nil {
			return streaming.EventFrame{}, err
		}
		return streaming.EventFrame{Data: data}, nil
	}
	return streaming.EventFrame{}, fmt.Errorf("no field set in %T", e)
}
