// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package fake

import (
	"context"
	"errors"
	"fmt"
	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
	"ssegroup"
	"strings"
	"sync"
)

// SseProtocolServer is a fake server for instances of the ssegroup.SseProtocolClient type.
type SseProtocolServer struct {
	// SseProtocolDataServer contains the fakes for client SseProtocolDataClient
	SseProtocolDataServer SseProtocolDataServer

	// OpenID is the fake for method SseProtocolClient.OpenID
	// HTTP status codes to indicate success: http.StatusOK
	OpenID func(ctx context.Context, options *ssegroup.SseProtocolClientOpenIDOptions) (resp azfake.SSEResponder[ssegroup.ProtocolEvents], errResp azfake.ErrorResponder)

	// OpenInvalidID is the fake for method SseProtocolClient.OpenInvalidID
	// HTTP status codes to indicate success: http.StatusOK
	OpenInvalidID func(ctx context.Context, options *ssegroup.SseProtocolClientOpenInvalidIDOptions) (resp azfake.SSEResponder[ssegroup.ProtocolEvents], errResp azfake.ErrorResponder)

	// OpenInvalidRetry is the fake for method SseProtocolClient.OpenInvalidRetry
	// HTTP status codes to indicate success: http.StatusOK
	OpenInvalidRetry func(ctx context.Context, options *ssegroup.SseProtocolClientOpenInvalidRetryOptions) (resp azfake.SSEResponder[ssegroup.ProtocolEvents], errResp azfake.ErrorResponder)

	// OpenReconnect is the fake for method SseProtocolClient.OpenReconnect
	// HTTP status codes to indicate success: http.StatusOK
	OpenReconnect func(ctx context.Context, options *ssegroup.SseProtocolClientOpenReconnectOptions) (resp azfake.SSEResponder[ssegroup.ProtocolEvents], errResp azfake.ErrorResponder)

	// OpenRetry is the fake for method SseProtocolClient.OpenRetry
	// HTTP status codes to indicate success: http.StatusOK
	OpenRetry func(ctx context.Context, options *ssegroup.SseProtocolClientOpenRetryOptions) (resp azfake.SSEResponder[ssegroup.ProtocolEvents], errResp azfake.ErrorResponder)
}

// NewSseProtocolServerTransport creates a new instance of SseProtocolServerTransport with the provided implementation.
// The returned SseProtocolServerTransport instance is connected to an instance of ssegroup.SseProtocolClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewSseProtocolServerTransport(srv *SseProtocolServer) *SseProtocolServerTransport {
	return &SseProtocolServerTransport{srv: srv}
}

// SseProtocolServerTransport connects instances of ssegroup.SseProtocolClient to instances of SseProtocolServer.
// Don't use this type directly, use NewSseProtocolServerTransport instead.
type SseProtocolServerTransport struct {
	srv                     *SseProtocolServer
	trMu                    sync.Mutex
	trSseProtocolDataServer *SseProtocolDataServerTransport
}

// Do implements the policy.Transporter interface for SseProtocolServerTransport.
func (s *SseProtocolServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	if client := method[:strings.Index(method, ".")]; client != "SseProtocolClient" {
		return s.dispatchToClientFake(req, client)
	}
	return s.dispatchToMethodFake(req, method)
}

func (s *SseProtocolServerTransport) dispatchToClientFake(req *http.Request, client string) (*http.Response, error) {
	var resp *http.Response
	var err error

	switch client {
	case "SseProtocolDataClient":
		initServer(&s.trMu, &s.trSseProtocolDataServer, func() *SseProtocolDataServerTransport {
			return NewSseProtocolDataServerTransport(&s.srv.SseProtocolDataServer)
		})
		resp, err = s.trSseProtocolDataServer.Do(req)
	default:
		err = fmt.Errorf("unhandled client %s", client)
	}

	return resp, err
}

func (s *SseProtocolServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result, 1)
	go func() {
		var intercepted bool
		var res result
		if sseProtocolServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = sseProtocolServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "SseProtocolClient.OpenID":
				res.resp, res.err = s.dispatchOpenID(req)
			case "SseProtocolClient.OpenInvalidID":
				res.resp, res.err = s.dispatchOpenInvalidID(req)
			case "SseProtocolClient.OpenInvalidRetry":
				res.resp, res.err = s.dispatchOpenInvalidRetry(req)
			case "SseProtocolClient.OpenReconnect":
				res.resp, res.err = s.dispatchOpenReconnect(req)
			case "SseProtocolClient.OpenRetry":
				res.resp, res.err = s.dispatchOpenRetry(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		resultChan <- res
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (s *SseProtocolServerTransport) dispatchOpenID(req *http.Request) (*http.Response, error) {
	if s.srv.OpenID == nil {
		return nil, &nonRetriableError{errors.New("fake for method OpenID not implemented")}
	}
	var options *ssegroup.SseProtocolClientOpenIDOptions
	if req.Header.Get("Last-Event-ID") != "" {
		options = &ssegroup.SseProtocolClientOpenIDOptions{
			LastEventID: req.Header.Get("Last-Event-ID"),
		}
	}
	respr, errRespr := s.srv.OpenID(req.Context(), options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeProtocolEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchOpenInvalidID(req *http.Request) (*http.Response, error) {
	if s.srv.OpenInvalidID == nil {
		return nil, &nonRetriableError{errors.New("fake for method OpenInvalidID not implemented")}
	}
	var options *ssegroup.SseProtocolClientOpenInvalidIDOptions
	if req.Header.Get("Last-Event-ID") != "" {
		options = &ssegroup.SseProtocolClientOpenInvalidIDOptions{
			LastEventID: req.Header.Get("Last-Event-ID"),
		}
	}
	respr, errRespr := s.srv.OpenInvalidID(req.Context(), options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeProtocolEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchOpenInvalidRetry(req *http.Request) (*http.Response, error) {
	if s.srv.OpenInvalidRetry == nil {
		return nil, &nonRetriableError{errors.New("fake for method OpenInvalidRetry not implemented")}
	}
	var options *ssegroup.SseProtocolClientOpenInvalidRetryOptions
	if req.Header.Get("Last-Event-ID") != "" {
		options = &ssegroup.SseProtocolClientOpenInvalidRetryOptions{
			LastEventID: req.Header.Get("Last-Event-ID"),
		}
	}
	respr, errRespr := s.srv.OpenInvalidRetry(req.Context(), options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeProtocolEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchOpenReconnect(req *http.Request) (*http.Response, error) {
	if s.srv.OpenReconnect == nil {
		return nil, &nonRetriableError{errors.New("fake for method OpenReconnect not implemented")}
	}
	var options *ssegroup.SseProtocolClientOpenReconnectOptions
	if req.Header.Get("Last-Event-ID") != "" {
		options = &ssegroup.SseProtocolClientOpenReconnectOptions{
			LastEventID: req.Header.Get("Last-Event-ID"),
		}
	}
	respr, errRespr := s.srv.OpenReconnect(req.Context(), options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeProtocolEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (s *SseProtocolServerTransport) dispatchOpenRetry(req *http.Request) (*http.Response, error) {
	if s.srv.OpenRetry == nil {
		return nil, &nonRetriableError{errors.New("fake for method OpenRetry not implemented")}
	}
	var options *ssegroup.SseProtocolClientOpenRetryOptions
	if req.Header.Get("Last-Event-ID") != "" {
		options = &ssegroup.SseProtocolClientOpenRetryOptions{
			LastEventID: req.Header.Get("Last-Event-ID"),
		}
	}
	respr, errRespr := s.srv.OpenRetry(req.Context(), options)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	body, err := server.MarshalSSEResponder(&respr, encodeProtocolEvents)
	if err != nil {
		return nil, err
	}
	resp, err := server.NewResponse(server.ResponseContent{HTTPStatus: http.StatusOK}, req, &server.ResponseOptions{
		Body:        body,
		ContentType: "text/event-stream",
	})
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to SseProtocolServerTransport
var sseProtocolServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
