// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

type FinalResult struct {
	// REQUIRED
	References []*string
}

type Info struct {
	// REQUIRED
	Desc *string
}

type PartialResult struct {
	// REQUIRED
	Text *string
}

type ProtocolInfo struct {
	// REQUIRED
	Message *string
}

type ResponseCreated struct {
	// REQUIRED
	ID *string
}

type ResponseDelta struct {
	// REQUIRED
	Delta *string
}

type RetrievalRequest struct {
	// REQUIRED
	Query *string
}

type WithEnvelope struct {
	// REQUIRED
	Contents *string
}

type WithEnvelope1 struct {
	// REQUIRED
	Contents *string

	// REQUIRED
	Metadata map[string]*string
}
