// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

// SseNamedClientOpenReceiveOptions contains the optional parameters for the SseNamedClient.OpenReceive method.
type SseNamedClientOpenReceiveOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolClientOpenIDOptions contains the optional parameters for the SseProtocolClient.OpenID method.
type SseProtocolClientOpenIDOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolClientOpenInvalidIDOptions contains the optional parameters for the SseProtocolClient.OpenInvalidID method.
type SseProtocolClientOpenInvalidIDOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolClientOpenInvalidRetryOptions contains the optional parameters for the SseProtocolClient.OpenInvalidRetry method.
type SseProtocolClientOpenInvalidRetryOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolClientOpenReconnectOptions contains the optional parameters for the SseProtocolClient.OpenReconnect method.
type SseProtocolClientOpenReconnectOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolClientOpenRetryOptions contains the optional parameters for the SseProtocolClient.OpenRetry method.
type SseProtocolClientOpenRetryOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolDataClientOpenWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.OpenWithEnvelope
// method.
type SseProtocolDataClientOpenWithEnvelopeOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseProtocolDataClientOpenWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.OpenWithoutEnvelope
// method.
type SseProtocolDataClientOpenWithoutEnvelopeOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseRetrieveClientOpenStreamOptions contains the optional parameters for the SseRetrieveClient.OpenStream method.
type SseRetrieveClientOpenStreamOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}

// SseUnnamedClientOpenReceiveOptions contains the optional parameters for the SseUnnamedClient.OpenReceive method.
type SseUnnamedClientOpenReceiveOptions struct {
	// Sets the Last-Event-ID request header. Use only when the service supports resuming from an event ID. The default is empty,
	// which omits the header. This option does not enable automatic reconnection.
	LastEventID string
}
