// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

// SseNamedClientReceiveOptions contains the optional parameters for the SseNamedClient.Receive method.
type SseNamedClientOpenReceiveOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientIDOptions contains the optional parameters for the SseProtocolClient.ID method.
type SseProtocolClientOpenIDOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientInvalidIDOptions contains the optional parameters for the SseProtocolClient.InvalidID method.
type SseProtocolClientOpenInvalidIDOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientInvalidRetryOptions contains the optional parameters for the SseProtocolClient.InvalidRetry method.
type SseProtocolClientOpenInvalidRetryOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientReconnectOptions contains the optional parameters for the SseProtocolClient.Reconnect method.
type SseProtocolClientOpenReconnectOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientRetryOptions contains the optional parameters for the SseProtocolClient.Retry method.
type SseProtocolClientOpenRetryOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolDataClientWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithEnvelope method.
type SseProtocolDataClientOpenWithEnvelopeOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolDataClientWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithoutEnvelope
// method.
type SseProtocolDataClientOpenWithoutEnvelopeOptions struct {
	// placeholder for future optional parameters
}

// SseRetrieveClientStreamOptions contains the optional parameters for the SseRetrieveClient.Stream method.
type SseRetrieveClientOpenStreamOptions struct {
	// placeholder for future optional parameters
}

// SseUnnamedClientReceiveOptions contains the optional parameters for the SseUnnamedClient.Receive method.
type SseUnnamedClientOpenReceiveOptions struct {
	// placeholder for future optional parameters
}
