// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

// SseNamedClientReceiveOptions contains the optional parameters for the SseNamedClient.Receive method.
type SseNamedClientReceiveOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientIDOptions contains the optional parameters for the SseProtocolClient.ID method.
type SseProtocolClientIDOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientInvalidIDOptions contains the optional parameters for the SseProtocolClient.InvalidID method.
type SseProtocolClientInvalidIDOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientInvalidRetryOptions contains the optional parameters for the SseProtocolClient.InvalidRetry method.
type SseProtocolClientInvalidRetryOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientReconnectOptions contains the optional parameters for the SseProtocolClient.Reconnect method.
type SseProtocolClientReconnectOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolClientRetryOptions contains the optional parameters for the SseProtocolClient.Retry method.
type SseProtocolClientRetryOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolDataClientWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithEnvelope method.
type SseProtocolDataClientWithEnvelopeOptions struct {
	// placeholder for future optional parameters
}

// SseProtocolDataClientWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithoutEnvelope
// method.
type SseProtocolDataClientWithoutEnvelopeOptions struct {
	// placeholder for future optional parameters
}

// SseRetrieveClientStreamOptions contains the optional parameters for the SseRetrieveClient.Stream method.
type SseRetrieveClientStreamOptions struct {
	// placeholder for future optional parameters
}

// SseUnnamedClientReceiveOptions contains the optional parameters for the SseUnnamedClient.Receive method.
type SseUnnamedClientReceiveOptions struct {
	// placeholder for future optional parameters
}
