// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import "github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"

// SseNamedClientOpenReceiveResponse contains the response from method SseNamedClient.OpenReceive.
type SseNamedClientOpenReceiveResponse struct {
	Stream *streaming.EventReader[ResponseEvents]
}

// SseProtocolClientOpenIDResponse contains the response from method SseProtocolClient.OpenID.
type SseProtocolClientOpenIDResponse struct {
	Stream *streaming.EventReader[ProtocolEvents]
}

// SseProtocolClientOpenInvalidIDResponse contains the response from method SseProtocolClient.OpenInvalidID.
type SseProtocolClientOpenInvalidIDResponse struct {
	Stream *streaming.EventReader[ProtocolEvents]
}

// SseProtocolClientOpenInvalidRetryResponse contains the response from method SseProtocolClient.OpenInvalidRetry.
type SseProtocolClientOpenInvalidRetryResponse struct {
	Stream *streaming.EventReader[ProtocolEvents]
}

// SseProtocolClientOpenReconnectResponse contains the response from method SseProtocolClient.OpenReconnect.
type SseProtocolClientOpenReconnectResponse struct {
	Stream *streaming.EventReader[ProtocolEvents]
}

// SseProtocolClientOpenRetryResponse contains the response from method SseProtocolClient.OpenRetry.
type SseProtocolClientOpenRetryResponse struct {
	Stream *streaming.EventReader[ProtocolEvents]
}

// SseProtocolDataClientOpenWithEnvelopeResponse contains the response from method SseProtocolDataClient.OpenWithEnvelope.
type SseProtocolDataClientOpenWithEnvelopeResponse struct {
	Stream *streaming.EventReader[DataEvents]
}

// SseProtocolDataClientOpenWithoutEnvelopeResponse contains the response from method SseProtocolDataClient.OpenWithoutEnvelope.
type SseProtocolDataClientOpenWithoutEnvelopeResponse struct {
	Stream *streaming.EventReader[DataEvents]
}

// SseRetrieveClientOpenStreamResponse contains the response from method SseRetrieveClient.OpenStream.
type SseRetrieveClientOpenStreamResponse struct {
	Stream *streaming.EventReader[RetrievalEvents]
}

// SseUnnamedClientOpenReceiveResponse contains the response from method SseUnnamedClient.OpenReceive.
type SseUnnamedClientOpenReceiveResponse struct {
	Stream *streaming.EventReader[UnnamedEvents]
}
