// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

// SseNamedClientReceiveResponse contains the response from method SseNamedClient.Receive.
type SseNamedClientReceiveResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ResponseEvents]
}

// SseProtocolClientIDResponse contains the response from method SseProtocolClient.ID.
type SseProtocolClientIDResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ProtocolEvents]
}

// SseProtocolClientInvalidIDResponse contains the response from method SseProtocolClient.InvalidID.
type SseProtocolClientInvalidIDResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ProtocolEvents]
}

// SseProtocolClientInvalidRetryResponse contains the response from method SseProtocolClient.InvalidRetry.
type SseProtocolClientInvalidRetryResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ProtocolEvents]
}

// SseProtocolClientReconnectResponse contains the response from method SseProtocolClient.Reconnect.
type SseProtocolClientReconnectResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ProtocolEvents]
}

// SseProtocolClientRetryResponse contains the response from method SseProtocolClient.Retry.
type SseProtocolClientRetryResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[ProtocolEvents]
}

// SseProtocolDataClientWithEnvelopeResponse contains the response from method SseProtocolDataClient.WithEnvelope.
type SseProtocolDataClientWithEnvelopeResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[DataEvents]
}

// SseProtocolDataClientWithoutEnvelopeResponse contains the response from method SseProtocolDataClient.WithoutEnvelope.
type SseProtocolDataClientWithoutEnvelopeResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[DataEvents]
}

// SseRetrieveClientStreamResponse contains the response from method SseRetrieveClient.Stream.
type SseRetrieveClientStreamResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[RetrievalEvents]
}

// SseUnnamedClientReceiveResponse contains the response from method SseUnnamedClient.Receive.
type SseUnnamedClientReceiveResponse struct {
	// Stream contains the Server-Sent Events for the response.
	Stream *EventStream[UnnamedEvents]
}
