// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import "github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"

// SseNamedClientReceiveResponse contains the response from method SseNamedClient.Receive.
type SseNamedClientReceiveResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ResponseEvents]
}

// SseProtocolClientIDResponse contains the response from method SseProtocolClient.ID.
type SseProtocolClientIDResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ProtocolEvents]
}

// SseProtocolClientInvalidIDResponse contains the response from method SseProtocolClient.InvalidID.
type SseProtocolClientInvalidIDResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ProtocolEvents]
}

// SseProtocolClientInvalidRetryResponse contains the response from method SseProtocolClient.InvalidRetry.
type SseProtocolClientInvalidRetryResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ProtocolEvents]
}

// SseProtocolClientReconnectResponse contains the response from method SseProtocolClient.Reconnect.
type SseProtocolClientReconnectResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ProtocolEvents]
}

// SseProtocolClientRetryResponse contains the response from method SseProtocolClient.Retry.
type SseProtocolClientRetryResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[ProtocolEvents]
}

// SseProtocolDataClientWithEnvelopeResponse contains the response from method SseProtocolDataClient.WithEnvelope.
type SseProtocolDataClientWithEnvelopeResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[DataEvents]
}

// SseProtocolDataClientWithoutEnvelopeResponse contains the response from method SseProtocolDataClient.WithoutEnvelope.
type SseProtocolDataClientWithoutEnvelopeResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[DataEvents]
}

// SseRetrieveClientStreamResponse contains the response from method SseRetrieveClient.Stream.
type SseRetrieveClientStreamResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[RetrievalEvents]
}

// SseUnnamedClientReceiveResponse contains the response from method SseUnnamedClient.Receive.
type SseUnnamedClientReceiveResponse struct {
	// Stream is the typed reader for the response's Server-Sent Events. It is
	// never nil; an empty stream simply yields no events.
	Stream *streaming.Event[UnnamedEvents]
}
