// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
	"io"
	"net/http"
)

// SseNamedClient contains the methods for the SseNamed group.
// Don't use this type directly, use [SseClient.NewSseNamedClient] instead.
type SseNamedClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenReceive -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseNamedClientOpenReceiveOptions contains the optional parameters for the SseNamedClient.OpenReceive method.
func (client *SseNamedClient) OpenReceive(ctx context.Context, options *SseNamedClientOpenReceiveOptions) (SseNamedClientOpenReceiveResponse, error) {
	var err error
	const operationName = "SseNamedClient.OpenReceive"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	connectionOptions := SseNamedClientOpenReceiveOptions{}
	if options != nil {
		connectionOptions = *options
	}
	connect := func(ctx context.Context, lastEventID string) (io.ReadCloser, error) {
		connectionOptions.LastEventID = lastEventID
		return client.receive(ctx, &connectionOptions)
	}
	reader, err := streaming.NewEventReader(ctx, connect, streaming.EventHandler[ResponseEvents]{
		Decode: decodeResponseEvents,
	}, &streaming.EventReaderOptions{LastEventID: connectionOptions.LastEventID})
	if err != nil {
		return SseNamedClientOpenReceiveResponse{}, err
	}
	return SseNamedClientOpenReceiveResponse{Stream: reader}, nil
}

// receive opens a connection for the OpenReceive stream.
func (client *SseNamedClient) receive(ctx context.Context, options *SseNamedClientOpenReceiveOptions) (io.ReadCloser, error) {
	req, err := client.receiveCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	return runtime.SSEResponse(httpResp, err, http.StatusOK)
}

// receiveCreateRequest creates the OpenReceive request.
func (client *SseNamedClient) receiveCreateRequest(ctx context.Context, _ *SseNamedClientOpenReceiveOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/named/receive"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
