// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseUnnamedClient contains the methods for the SseUnnamed group.
// Don't use this type directly, use [SseClient.NewSseUnnamedClient] instead.
type SseUnnamedClient struct {
	internal *azcore.Client
	endpoint string
}

// NewReceiveEventStream opens the Receive Server-Sent Events stream. The initial
// connection is established before returning.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseUnnamedClientReceiveOptions contains the optional parameters for the SseUnnamedClient.Receive method.
func (client *SseUnnamedClient) NewReceiveEventStream(ctx context.Context, options *SseUnnamedClientReceiveOptions) (*streaming.Event[UnnamedEvents], error) {
	return streaming.NewEvent(ctx, streaming.EventStreamHandler[UnnamedEvents]{
		Decode:  decodeUnnamedEvents,
		Connect: client.receiveConnect(options),
	})
}

// receiveConnect returns the connection factory for the Receive stream.
func (client *SseUnnamedClient) receiveConnect(options *SseUnnamedClientReceiveOptions) func(context.Context, string) (*http.Response, error) {
	return func(ctx context.Context, lastEventID string) (*http.Response, error) {
		ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseUnnamedClient.Receive")
		req, err := client.receiveCreateRequest(ctx, options)
		if err != nil {
			return nil, err
		}
		if lastEventID != "" {
			req.Raw().Header.Set("Last-Event-ID", lastEventID)
		}
		resp, err := client.internal.Pipeline().Do(req)
		if err != nil {
			return nil, err
		}
		if !runtime.HasStatusCode(resp, http.StatusOK) {
			return nil, runtime.NewResponseError(resp)
		}
		return resp, nil
	}
}

// receiveCreateRequest creates the Receive request.
func (client *SseUnnamedClient) receiveCreateRequest(ctx context.Context, _ *SseUnnamedClientReceiveOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/unnamed/receive"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
