// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
	"io"
	"net/http"
)

// SseRetrieveClient contains the methods for the SseRetrieve group.
// Don't use this type directly, use [SseClient.NewSseRetrieveClient] instead.
type SseRetrieveClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenStream -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseRetrieveClientOpenStreamOptions contains the optional parameters for the SseRetrieveClient.OpenStream method.
func (client *SseRetrieveClient) OpenStream(ctx context.Context, request RetrievalRequest, options *SseRetrieveClientOpenStreamOptions) (SseRetrieveClientOpenStreamResponse, error) {
	var err error
	const operationName = "SseRetrieveClient.OpenStream"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	connectionOptions := SseRetrieveClientOpenStreamOptions{}
	if options != nil {
		connectionOptions = *options
	}
	connect := func(ctx context.Context, lastEventID string) (io.ReadCloser, error) {
		connectionOptions.LastEventID = lastEventID
		return client.stream(ctx, request, &connectionOptions)
	}
	reader, err := streaming.NewEventReader(ctx, connect, streaming.EventHandler[RetrievalEvents]{
		Decode: decodeRetrievalEvents,
	}, &streaming.EventReaderOptions{LastEventID: connectionOptions.LastEventID})
	if err != nil {
		return SseRetrieveClientOpenStreamResponse{}, err
	}
	return SseRetrieveClientOpenStreamResponse{Stream: reader}, nil
}

// stream opens a connection for the OpenStream stream.
func (client *SseRetrieveClient) stream(ctx context.Context, request RetrievalRequest, options *SseRetrieveClientOpenStreamOptions) (io.ReadCloser, error) {
	req, err := client.streamCreateRequest(ctx, request, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	return runtime.SSEResponse(httpResp, err, http.StatusOK)
}

// streamCreateRequest creates the OpenStream request.
func (client *SseRetrieveClient) streamCreateRequest(ctx context.Context, request RetrievalRequest, _ *SseRetrieveClientOpenStreamOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/retrieve/stream"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, request); err != nil {
		return nil, err
	}
	return req, nil
}
