// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseRetrieveClient contains the methods for the SseRetrieve group.
// Don't use this type directly, use [SseClient.NewSseRetrieveClient] instead.
type SseRetrieveClient struct {
	internal *azcore.Client
	endpoint string
}

// Stream -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseRetrieveClientStreamOptions contains the optional parameters for the SseRetrieveClient.Stream method.
func (client *SseRetrieveClient) Stream(ctx context.Context, request RetrievalRequest, options *SseRetrieveClientStreamOptions) (SseRetrieveClientStreamResponse, error) {
	var err error
	const operationName = "SseRetrieveClient.Stream"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.streamCreateRequest(ctx, request, options)
	if err != nil {
		return SseRetrieveClientStreamResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseRetrieveClientStreamResponse{}, err
	}
	return client.streamHandleResponse(httpResp, http.StatusOK)
}

// streamCreateRequest creates the Stream request.
func (client *SseRetrieveClient) streamCreateRequest(ctx context.Context, request RetrievalRequest, _ *SseRetrieveClientStreamOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/retrieve/stream"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, request); err != nil {
		return nil, err
	}
	return req, nil
}

// streamHandleResponse handles the Stream response.
func (client *SseRetrieveClient) streamHandleResponse(resp *http.Response, successCodes ...int) (SseRetrieveClientStreamResponse, error) {
	result := SseRetrieveClientStreamResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = NewEventStream[RetrievalEvents](resp.Body, decodeRetrievalEvents)
	return result, nil
}
