// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
	"net/http"
)

// SseProtocolClient contains the methods for the SseProtocol group.
// Don't use this type directly, use [SseClient.NewSseProtocolClient] instead.
type SseProtocolClient struct {
	internal *azcore.Client
	endpoint string
}

// NewSseProtocolDataClient creates a new instance of [SseProtocolDataClient].
func (client *SseProtocolClient) NewSseProtocolDataClient() *SseProtocolDataClient {
	return &SseProtocolDataClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// OpenID -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientOpenIDOptions contains the optional parameters for the SseProtocolClient.OpenID method.
func (client *SseProtocolClient) OpenID(ctx context.Context, options *SseProtocolClientOpenIDOptions) (SseProtocolClientOpenIDResponse, error) {
	var err error
	const operationName = "SseProtocolClient.OpenID"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	resp, err := client.id(ctx, options)
	if err != nil {
		return SseProtocolClientOpenIDResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
	}, nil)
	if err != nil {
		return SseProtocolClientOpenIDResponse{}, err
	}
	return SseProtocolClientOpenIDResponse{Stream: reader}, nil
}

// id opens a connection for the OpenID stream.
func (client *SseProtocolClient) id(ctx context.Context, options *SseProtocolClientOpenIDOptions) (*http.Response, error) {
	req, err := client.idCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		return nil, runtime.NewResponseError(httpResp)
	}
	return httpResp, nil
}

// idCreateRequest creates the OpenID request.
func (client *SseProtocolClient) idCreateRequest(ctx context.Context, _ *SseProtocolClientOpenIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenInvalidID -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientOpenInvalidIDOptions contains the optional parameters for the SseProtocolClient.OpenInvalidID
//     method.
func (client *SseProtocolClient) OpenInvalidID(ctx context.Context, options *SseProtocolClientOpenInvalidIDOptions) (SseProtocolClientOpenInvalidIDResponse, error) {
	var err error
	const operationName = "SseProtocolClient.OpenInvalidID"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	resp, err := client.invalidID(ctx, options)
	if err != nil {
		return SseProtocolClientOpenInvalidIDResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
	}, nil)
	if err != nil {
		return SseProtocolClientOpenInvalidIDResponse{}, err
	}
	return SseProtocolClientOpenInvalidIDResponse{Stream: reader}, nil
}

// invalidID opens a connection for the OpenInvalidID stream.
func (client *SseProtocolClient) invalidID(ctx context.Context, options *SseProtocolClientOpenInvalidIDOptions) (*http.Response, error) {
	req, err := client.invalidIDCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		return nil, runtime.NewResponseError(httpResp)
	}
	return httpResp, nil
}

// invalidIDCreateRequest creates the OpenInvalidID request.
func (client *SseProtocolClient) invalidIDCreateRequest(ctx context.Context, _ *SseProtocolClientOpenInvalidIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenInvalidRetry -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientOpenInvalidRetryOptions contains the optional parameters for the SseProtocolClient.OpenInvalidRetry
//     method.
func (client *SseProtocolClient) OpenInvalidRetry(ctx context.Context, options *SseProtocolClientOpenInvalidRetryOptions) (SseProtocolClientOpenInvalidRetryResponse, error) {
	var err error
	const operationName = "SseProtocolClient.OpenInvalidRetry"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	resp, err := client.invalidRetry(ctx, options)
	if err != nil {
		return SseProtocolClientOpenInvalidRetryResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
	}, nil)
	if err != nil {
		return SseProtocolClientOpenInvalidRetryResponse{}, err
	}
	return SseProtocolClientOpenInvalidRetryResponse{Stream: reader}, nil
}

// invalidRetry opens a connection for the OpenInvalidRetry stream.
func (client *SseProtocolClient) invalidRetry(ctx context.Context, options *SseProtocolClientOpenInvalidRetryOptions) (*http.Response, error) {
	req, err := client.invalidRetryCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		return nil, runtime.NewResponseError(httpResp)
	}
	return httpResp, nil
}

// invalidRetryCreateRequest creates the OpenInvalidRetry request.
func (client *SseProtocolClient) invalidRetryCreateRequest(ctx context.Context, _ *SseProtocolClientOpenInvalidRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenReconnect -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientOpenReconnectOptions contains the optional parameters for the SseProtocolClient.OpenReconnect
//     method.
func (client *SseProtocolClient) OpenReconnect(ctx context.Context, options *SseProtocolClientOpenReconnectOptions) (SseProtocolClientOpenReconnectResponse, error) {
	var err error
	const operationName = "SseProtocolClient.OpenReconnect"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	resp, err := client.reconnect(ctx, options)
	if err != nil {
		return SseProtocolClientOpenReconnectResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
	}, nil)
	if err != nil {
		return SseProtocolClientOpenReconnectResponse{}, err
	}
	return SseProtocolClientOpenReconnectResponse{Stream: reader}, nil
}

// reconnect opens a connection for the OpenReconnect stream.
func (client *SseProtocolClient) reconnect(ctx context.Context, options *SseProtocolClientOpenReconnectOptions) (*http.Response, error) {
	req, err := client.reconnectCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		return nil, runtime.NewResponseError(httpResp)
	}
	return httpResp, nil
}

// reconnectCreateRequest creates the OpenReconnect request.
func (client *SseProtocolClient) reconnectCreateRequest(ctx context.Context, _ *SseProtocolClientOpenReconnectOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/reconnect"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenRetry -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientOpenRetryOptions contains the optional parameters for the SseProtocolClient.OpenRetry method.
func (client *SseProtocolClient) OpenRetry(ctx context.Context, options *SseProtocolClientOpenRetryOptions) (SseProtocolClientOpenRetryResponse, error) {
	var err error
	const operationName = "SseProtocolClient.OpenRetry"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	resp, err := client.retry(ctx, options)
	if err != nil {
		return SseProtocolClientOpenRetryResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
	}, nil)
	if err != nil {
		return SseProtocolClientOpenRetryResponse{}, err
	}
	return SseProtocolClientOpenRetryResponse{Stream: reader}, nil
}

// retry opens a connection for the OpenRetry stream.
func (client *SseProtocolClient) retry(ctx context.Context, options *SseProtocolClientOpenRetryOptions) (*http.Response, error) {
	req, err := client.retryCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		return nil, runtime.NewResponseError(httpResp)
	}
	return httpResp, nil
}

// retryCreateRequest creates the OpenRetry request.
func (client *SseProtocolClient) retryCreateRequest(ctx context.Context, _ *SseProtocolClientOpenRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
