// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
	"io"
	"net/http"
)

// SseUnnamedClient contains the methods for the SseUnnamed group.
// Don't use this type directly, use [SseClient.NewSseUnnamedClient] instead.
type SseUnnamedClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenReceive -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseUnnamedClientOpenReceiveOptions contains the optional parameters for the SseUnnamedClient.OpenReceive method.
func (client *SseUnnamedClient) OpenReceive(ctx context.Context, options *SseUnnamedClientOpenReceiveOptions) (SseUnnamedClientOpenReceiveResponse, error) {
	var err error
	const operationName = "SseUnnamedClient.OpenReceive"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	connectionOptions := SseUnnamedClientOpenReceiveOptions{}
	if options != nil {
		connectionOptions = *options
	}
	connect := func(ctx context.Context, lastEventID string) (io.ReadCloser, error) {
		connectionOptions.LastEventID = lastEventID
		return client.receive(ctx, &connectionOptions)
	}
	reader, err := streaming.NewEventReader(ctx, connect, streaming.EventHandler[UnnamedEvents]{
		Decode: decodeUnnamedEvents,
	}, &streaming.EventReaderOptions{LastEventID: connectionOptions.LastEventID})
	if err != nil {
		return SseUnnamedClientOpenReceiveResponse{}, err
	}
	return SseUnnamedClientOpenReceiveResponse{Stream: reader}, nil
}

// receive opens a connection for the OpenReceive stream.
func (client *SseUnnamedClient) receive(ctx context.Context, options *SseUnnamedClientOpenReceiveOptions) (io.ReadCloser, error) {
	req, err := client.receiveCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	return runtime.SSEResponse(httpResp, err, http.StatusOK)
}

// receiveCreateRequest creates the OpenReceive request.
func (client *SseUnnamedClient) receiveCreateRequest(ctx context.Context, _ *SseUnnamedClientOpenReceiveOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/unnamed/receive"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
