// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseNamedClient contains the methods for the SseNamed group.
// Don't use this type directly, use [SseClient.NewSseNamedClient] instead.
type SseNamedClient struct {
	internal *azcore.Client
	endpoint string
}

// NewReceiveEventStream opens the Receive Server-Sent Events stream. The initial
// connection is established before returning; an unexpected mid-stream
// disconnect is transparently reconnected via the Last-Event-ID header.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseNamedClientReceiveOptions contains the optional parameters for the SseNamedClient.Receive method.
func (client *SseNamedClient) NewReceiveEventStream(ctx context.Context, options *SseNamedClientReceiveOptions) (*streaming.Event[ResponseEvents], error) {
	return streaming.NewEvent(ctx, streaming.EventStreamHandler[ResponseEvents]{
		Decode:    decodeResponseEvents,
		Connect:   client.receiveConnect(options),
		Reconnect: true,
	})
}

// receiveConnect returns the connection factory for the Receive stream.
func (client *SseNamedClient) receiveConnect(options *SseNamedClientReceiveOptions) func(context.Context, string) (*http.Response, error) {
	return func(ctx context.Context, lastEventID string) (*http.Response, error) {
		ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseNamedClient.Receive")
		req, err := client.receiveCreateRequest(ctx, options)
		if err != nil {
			return nil, err
		}
		if lastEventID != "" {
			req.Raw().Header.Set("Last-Event-ID", lastEventID)
		}
		resp, err := client.internal.Pipeline().Do(req)
		if err != nil {
			return nil, err
		}
		if !runtime.HasStatusCode(resp, http.StatusOK) {
			return nil, runtime.NewResponseError(resp)
		}
		return resp, nil
	}
}

// receiveCreateRequest creates the Receive request.
func (client *SseNamedClient) receiveCreateRequest(ctx context.Context, _ *SseNamedClientReceiveOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/named/receive"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
