// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"

	"ssegroup/streaming"
)

// SseProtocolClient contains the methods for the SseProtocol group.
// Don't use this type directly, use [SseClient.NewSseProtocolClient] instead.
type SseProtocolClient struct {
	internal *azcore.Client
	endpoint string
}

// NewSseProtocolDataClient creates a new instance of [SseProtocolDataClient].
func (client *SseProtocolClient) NewSseProtocolDataClient() *SseProtocolDataClient {
	return &SseProtocolDataClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// ID -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientIDOptions contains the optional parameters for the SseProtocolClient.ID method.
func (client *SseProtocolClient) ID(ctx context.Context, options *SseProtocolClientIDOptions) (SseProtocolClientIDResponse, error) {
	var err error
	const operationName = "SseProtocolClient.ID"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.idCreateRequest(ctx, options)
	if err != nil {
		return SseProtocolClientIDResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseProtocolClientIDResponse{}, err
	}
	return client.idHandleResponse(httpResp, http.StatusOK)
}

// idCreateRequest creates the ID request.
func (client *SseProtocolClient) idCreateRequest(ctx context.Context, _ *SseProtocolClientIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// idHandleResponse handles the ID response.
func (client *SseProtocolClient) idHandleResponse(resp *http.Response, successCodes ...int) (SseProtocolClientIDResponse, error) {
	result := SseProtocolClientIDResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = streaming.NewEvent(resp.Body, decodeProtocolEvents)
	return result, nil
}

// InvalidID -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientInvalidIDOptions contains the optional parameters for the SseProtocolClient.InvalidID method.
func (client *SseProtocolClient) InvalidID(ctx context.Context, options *SseProtocolClientInvalidIDOptions) (SseProtocolClientInvalidIDResponse, error) {
	var err error
	const operationName = "SseProtocolClient.InvalidID"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.invalidIDCreateRequest(ctx, options)
	if err != nil {
		return SseProtocolClientInvalidIDResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseProtocolClientInvalidIDResponse{}, err
	}
	return client.invalidIDHandleResponse(httpResp, http.StatusOK)
}

// invalidIDCreateRequest creates the InvalidID request.
func (client *SseProtocolClient) invalidIDCreateRequest(ctx context.Context, _ *SseProtocolClientInvalidIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// invalidIDHandleResponse handles the InvalidID response.
func (client *SseProtocolClient) invalidIDHandleResponse(resp *http.Response, successCodes ...int) (SseProtocolClientInvalidIDResponse, error) {
	result := SseProtocolClientInvalidIDResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = streaming.NewEvent(resp.Body, decodeProtocolEvents)
	return result, nil
}

// InvalidRetry -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientInvalidRetryOptions contains the optional parameters for the SseProtocolClient.InvalidRetry
//     method.
func (client *SseProtocolClient) InvalidRetry(ctx context.Context, options *SseProtocolClientInvalidRetryOptions) (SseProtocolClientInvalidRetryResponse, error) {
	var err error
	const operationName = "SseProtocolClient.InvalidRetry"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.invalidRetryCreateRequest(ctx, options)
	if err != nil {
		return SseProtocolClientInvalidRetryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseProtocolClientInvalidRetryResponse{}, err
	}
	return client.invalidRetryHandleResponse(httpResp, http.StatusOK)
}

// invalidRetryCreateRequest creates the InvalidRetry request.
func (client *SseProtocolClient) invalidRetryCreateRequest(ctx context.Context, _ *SseProtocolClientInvalidRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// invalidRetryHandleResponse handles the InvalidRetry response.
func (client *SseProtocolClient) invalidRetryHandleResponse(resp *http.Response, successCodes ...int) (SseProtocolClientInvalidRetryResponse, error) {
	result := SseProtocolClientInvalidRetryResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = streaming.NewEvent(resp.Body, decodeProtocolEvents)
	return result, nil
}

// Reconnect -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientReconnectOptions contains the optional parameters for the SseProtocolClient.Reconnect method.
func (client *SseProtocolClient) Reconnect(ctx context.Context, options *SseProtocolClientReconnectOptions) (SseProtocolClientReconnectResponse, error) {
	var err error
	const operationName = "SseProtocolClient.Reconnect"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.reconnectCreateRequest(ctx, options)
	if err != nil {
		return SseProtocolClientReconnectResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseProtocolClientReconnectResponse{}, err
	}
	return client.reconnectHandleResponse(httpResp, http.StatusOK)
}

// reconnectCreateRequest creates the Reconnect request.
func (client *SseProtocolClient) reconnectCreateRequest(ctx context.Context, _ *SseProtocolClientReconnectOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/reconnect"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// reconnectHandleResponse handles the Reconnect response.
func (client *SseProtocolClient) reconnectHandleResponse(resp *http.Response, successCodes ...int) (SseProtocolClientReconnectResponse, error) {
	result := SseProtocolClientReconnectResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = streaming.NewEvent(resp.Body, decodeProtocolEvents)
	return result, nil
}

// Retry -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientRetryOptions contains the optional parameters for the SseProtocolClient.Retry method.
func (client *SseProtocolClient) Retry(ctx context.Context, options *SseProtocolClientRetryOptions) (SseProtocolClientRetryResponse, error) {
	var err error
	const operationName = "SseProtocolClient.Retry"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.retryCreateRequest(ctx, options)
	if err != nil {
		return SseProtocolClientRetryResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseProtocolClientRetryResponse{}, err
	}
	return client.retryHandleResponse(httpResp, http.StatusOK)
}

// retryCreateRequest creates the Retry request.
func (client *SseProtocolClient) retryCreateRequest(ctx context.Context, _ *SseProtocolClientRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// retryHandleResponse handles the Retry response.
func (client *SseProtocolClient) retryHandleResponse(resp *http.Response, successCodes ...int) (SseProtocolClientRetryResponse, error) {
	result := SseProtocolClientRetryResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = streaming.NewEvent(resp.Body, decodeProtocolEvents)
	return result, nil
}
