// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseRetrieveClient contains the methods for the SseRetrieve group.
// Don't use this type directly, use [SseClient.NewSseRetrieveClient] instead.
type SseRetrieveClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenStream opens the Stream Server-Sent Events stream. The initial connection
// is established before returning; an unexpected mid-stream disconnect is
// transparently reconnected via the Last-Event-ID header.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseRetrieveClientStreamOptions contains the optional parameters for the SseRetrieveClient.Stream method.
func (client *SseRetrieveClient) OpenStream(ctx context.Context, request RetrievalRequest, options *SseRetrieveClientStreamOptions) (SseRetrieveClientStreamResponse, error) {
	connect := func(ctx context.Context, lastEventID string) (*http.Response, error) {
		return client.streamConnect(ctx, lastEventID, request, options)
	}
	resp, err := connect(ctx, "")
	if err != nil {
		return SseRetrieveClientStreamResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[RetrievalEvents]{
		Decode:    decodeRetrievalEvents,
		Connect:   connect,
		Reconnect: true,
	}, nil)
	if err != nil {
		return SseRetrieveClientStreamResponse{}, err
	}
	return SseRetrieveClientStreamResponse{Stream: reader}, nil
}

// streamConnect opens a connection for the Stream stream.
func (client *SseRetrieveClient) streamConnect(ctx context.Context, lastEventID string, request RetrievalRequest, options *SseRetrieveClientStreamOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseRetrieveClient.Stream")
	req, err := client.streamCreateRequest(ctx, request, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// streamCreateRequest creates the Stream request.
func (client *SseRetrieveClient) streamCreateRequest(ctx context.Context, request RetrievalRequest, _ *SseRetrieveClientStreamOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/retrieve/stream"
	req, err := runtime.NewRequest(ctx, http.MethodPost, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	req.Raw().Header["Content-Type"] = []string{"application/json"}
	if err := runtime.MarshalAsJSON(req, request); err != nil {
		return nil, err
	}
	return req, nil
}
