// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseUnnamedClient contains the methods for the SseUnnamed group.
// Don't use this type directly, use [SseClient.NewSseUnnamedClient] instead.
type SseUnnamedClient struct {
	internal *azcore.Client
	endpoint string
}

// Receive -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseUnnamedClientReceiveOptions contains the optional parameters for the SseUnnamedClient.Receive method.
func (client *SseUnnamedClient) Receive(ctx context.Context, options *SseUnnamedClientReceiveOptions) (SseUnnamedClientReceiveResponse, error) {
	var err error
	const operationName = "SseUnnamedClient.Receive"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	req, err := client.receiveCreateRequest(ctx, options)
	if err != nil {
		return SseUnnamedClientReceiveResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SseUnnamedClientReceiveResponse{}, err
	}
	return client.receiveHandleResponse(httpResp, http.StatusOK)
}

// receiveCreateRequest creates the Receive request.
func (client *SseUnnamedClient) receiveCreateRequest(ctx context.Context, _ *SseUnnamedClientReceiveOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/unnamed/receive"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// receiveHandleResponse handles the Receive response.
func (client *SseUnnamedClient) receiveHandleResponse(resp *http.Response, successCodes ...int) (SseUnnamedClientReceiveResponse, error) {
	result := SseUnnamedClientReceiveResponse{}
	if !runtime.HasStatusCode(resp, successCodes...) {
		return result, runtime.NewResponseError(resp)
	}
	result.Stream = NewEventStream[UnnamedEvents](resp.Body, decodeUnnamedEvents)
	return result, nil
}
