// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseProtocolDataClient contains the methods for the SseProtocolData group.
// Don't use this type directly, use [SseProtocolClient.NewSseProtocolDataClient] instead.
type SseProtocolDataClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenWithEnvelope opens the WithEnvelope Server-Sent Events stream. The initial
// connection is established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithEnvelope
//     method.
func (client *SseProtocolDataClient) OpenWithEnvelope(ctx context.Context, options *SseProtocolDataClientWithEnvelopeOptions) (SseProtocolDataClientWithEnvelopeResponse, error) {
	connect := func(ctx context.Context, lastEventID string) (*http.Response, error) {
		return client.withEnvelopeConnect(ctx, lastEventID, options)
	}
	resp, err := connect(ctx, "")
	if err != nil {
		return SseProtocolDataClientWithEnvelopeResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[DataEvents]{
		Decode:  decodeDataEvents,
		Connect: connect,
	}, nil)
	if err != nil {
		return SseProtocolDataClientWithEnvelopeResponse{}, err
	}
	return SseProtocolDataClientWithEnvelopeResponse{Stream: reader}, nil
}

// withEnvelopeConnect opens a connection for the WithEnvelope stream.
func (client *SseProtocolDataClient) withEnvelopeConnect(ctx context.Context, lastEventID string, options *SseProtocolDataClientWithEnvelopeOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolDataClient.WithEnvelope")
	req, err := client.withEnvelopeCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// withEnvelopeCreateRequest creates the WithEnvelope request.
func (client *SseProtocolDataClient) withEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientWithEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/with-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenWithoutEnvelope opens the WithoutEnvelope Server-Sent Events stream. The
// initial connection is established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithoutEnvelope
//     method.
func (client *SseProtocolDataClient) OpenWithoutEnvelope(ctx context.Context, options *SseProtocolDataClientWithoutEnvelopeOptions) (SseProtocolDataClientWithoutEnvelopeResponse, error) {
	connect := func(ctx context.Context, lastEventID string) (*http.Response, error) {
		return client.withoutEnvelopeConnect(ctx, lastEventID, options)
	}
	resp, err := connect(ctx, "")
	if err != nil {
		return SseProtocolDataClientWithoutEnvelopeResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[DataEvents]{
		Decode:  decodeDataEvents,
		Connect: connect,
	}, nil)
	if err != nil {
		return SseProtocolDataClientWithoutEnvelopeResponse{}, err
	}
	return SseProtocolDataClientWithoutEnvelopeResponse{Stream: reader}, nil
}

// withoutEnvelopeConnect opens a connection for the WithoutEnvelope stream.
func (client *SseProtocolDataClient) withoutEnvelopeConnect(ctx context.Context, lastEventID string, options *SseProtocolDataClientWithoutEnvelopeOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolDataClient.WithoutEnvelope")
	req, err := client.withoutEnvelopeCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// withoutEnvelopeCreateRequest creates the WithoutEnvelope request.
func (client *SseProtocolDataClient) withoutEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientWithoutEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/without-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
