// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
	"io"
	"net/http"
)

// SseProtocolDataClient contains the methods for the SseProtocolData group.
// Don't use this type directly, use [SseProtocolClient.NewSseProtocolDataClient] instead.
type SseProtocolDataClient struct {
	internal *azcore.Client
	endpoint string
}

// OpenWithEnvelope -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientOpenWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.OpenWithEnvelope
//     method.
func (client *SseProtocolDataClient) OpenWithEnvelope(ctx context.Context, options *SseProtocolDataClientOpenWithEnvelopeOptions) (SseProtocolDataClientOpenWithEnvelopeResponse, error) {
	var err error
	const operationName = "SseProtocolDataClient.OpenWithEnvelope"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	connectionOptions := SseProtocolDataClientOpenWithEnvelopeOptions{}
	if options != nil {
		connectionOptions = *options
	}
	connect := func(ctx context.Context, lastEventID string) (io.ReadCloser, error) {
		connectionOptions.LastEventID = lastEventID
		return client.withEnvelope(ctx, &connectionOptions)
	}
	reader, err := streaming.NewEventReader(ctx, connect, streaming.EventHandler[DataEvents]{
		Decode: decodeDataEvents,
	}, &streaming.EventReaderOptions{LastEventID: connectionOptions.LastEventID})
	if err != nil {
		return SseProtocolDataClientOpenWithEnvelopeResponse{}, err
	}
	return SseProtocolDataClientOpenWithEnvelopeResponse{Stream: reader}, nil
}

// withEnvelope opens a connection for the OpenWithEnvelope stream.
func (client *SseProtocolDataClient) withEnvelope(ctx context.Context, options *SseProtocolDataClientOpenWithEnvelopeOptions) (io.ReadCloser, error) {
	req, err := client.withEnvelopeCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	return runtime.SSEResponse(httpResp, err, http.StatusOK)
}

// withEnvelopeCreateRequest creates the OpenWithEnvelope request.
func (client *SseProtocolDataClient) withEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientOpenWithEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/with-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenWithoutEnvelope -
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientOpenWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.OpenWithoutEnvelope
//     method.
func (client *SseProtocolDataClient) OpenWithoutEnvelope(ctx context.Context, options *SseProtocolDataClientOpenWithoutEnvelopeOptions) (SseProtocolDataClientOpenWithoutEnvelopeResponse, error) {
	var err error
	const operationName = "SseProtocolDataClient.OpenWithoutEnvelope"
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, operationName)
	ctx, endSpan := runtime.StartSpan(ctx, operationName, client.internal.Tracer(), nil)
	defer func() { endSpan(err) }()
	connectionOptions := SseProtocolDataClientOpenWithoutEnvelopeOptions{}
	if options != nil {
		connectionOptions = *options
	}
	connect := func(ctx context.Context, lastEventID string) (io.ReadCloser, error) {
		connectionOptions.LastEventID = lastEventID
		return client.withoutEnvelope(ctx, &connectionOptions)
	}
	reader, err := streaming.NewEventReader(ctx, connect, streaming.EventHandler[DataEvents]{
		Decode: decodeDataEvents,
	}, &streaming.EventReaderOptions{LastEventID: connectionOptions.LastEventID})
	if err != nil {
		return SseProtocolDataClientOpenWithoutEnvelopeResponse{}, err
	}
	return SseProtocolDataClientOpenWithoutEnvelopeResponse{Stream: reader}, nil
}

// withoutEnvelope opens a connection for the OpenWithoutEnvelope stream.
func (client *SseProtocolDataClient) withoutEnvelope(ctx context.Context, options *SseProtocolDataClientOpenWithoutEnvelopeOptions) (io.ReadCloser, error) {
	req, err := client.withoutEnvelopeCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if options != nil && options.LastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", options.LastEventID)
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	return runtime.SSEResponse(httpResp, err, http.StatusOK)
}

// withoutEnvelopeCreateRequest creates the OpenWithoutEnvelope request.
func (client *SseProtocolDataClient) withoutEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientOpenWithoutEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/without-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
