// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseProtocolClient contains the methods for the SseProtocol group.
// Don't use this type directly, use [SseClient.NewSseProtocolClient] instead.
type SseProtocolClient struct {
	internal *azcore.Client
	endpoint string
}

// NewSseProtocolDataClient creates a new instance of [SseProtocolDataClient].
func (client *SseProtocolClient) NewSseProtocolDataClient() *SseProtocolDataClient {
	return &SseProtocolDataClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// OpenID opens the ID Server-Sent Events stream. The initial connection is
// established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientIDOptions contains the optional parameters for the SseProtocolClient.ID method.
func (client *SseProtocolClient) OpenID(ctx context.Context, options *SseProtocolClientOpenIDOptions) (SseProtocolClientOpenIDResponse, error) {
	resp, err := client.idConnect(ctx, "", options)
	if err != nil {
		return SseProtocolClientOpenIDResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
		Connect: func(ctx context.Context, lastEventID string) (*http.Response, error) {
			return client.idConnect(ctx, lastEventID, options)
		},
	}, nil)
	if err != nil {
		return SseProtocolClientOpenIDResponse{}, err
	}
	return SseProtocolClientOpenIDResponse{Stream: reader}, nil
}

// idConnect opens a connection for the ID stream.
func (client *SseProtocolClient) idConnect(ctx context.Context, lastEventID string, options *SseProtocolClientOpenIDOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolClient.ID")
	req, err := client.idCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// idCreateRequest creates the ID request.
func (client *SseProtocolClient) idCreateRequest(ctx context.Context, _ *SseProtocolClientOpenIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenInvalidID opens the InvalidID Server-Sent Events stream. The initial
// connection is established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientInvalidIDOptions contains the optional parameters for the SseProtocolClient.InvalidID method.
func (client *SseProtocolClient) OpenInvalidID(ctx context.Context, options *SseProtocolClientOpenInvalidIDOptions) (SseProtocolClientOpenInvalidIDResponse, error) {
	resp, err := client.invalidIDConnect(ctx, "", options)
	if err != nil {
		return SseProtocolClientOpenInvalidIDResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
		Connect: func(ctx context.Context, lastEventID string) (*http.Response, error) {
			return client.invalidIDConnect(ctx, lastEventID, options)
		},
	}, nil)
	if err != nil {
		return SseProtocolClientOpenInvalidIDResponse{}, err
	}
	return SseProtocolClientOpenInvalidIDResponse{Stream: reader}, nil
}

// invalidIDConnect opens a connection for the InvalidID stream.
func (client *SseProtocolClient) invalidIDConnect(ctx context.Context, lastEventID string, options *SseProtocolClientOpenInvalidIDOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolClient.InvalidID")
	req, err := client.invalidIDCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// invalidIDCreateRequest creates the InvalidID request.
func (client *SseProtocolClient) invalidIDCreateRequest(ctx context.Context, _ *SseProtocolClientOpenInvalidIDOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-id"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenInvalidRetry opens the InvalidRetry Server-Sent Events stream. The initial
// connection is established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientInvalidRetryOptions contains the optional parameters for the SseProtocolClient.InvalidRetry
//     method.
func (client *SseProtocolClient) OpenInvalidRetry(ctx context.Context, options *SseProtocolClientOpenInvalidRetryOptions) (SseProtocolClientOpenInvalidRetryResponse, error) {
	resp, err := client.invalidRetryConnect(ctx, "", options)
	if err != nil {
		return SseProtocolClientOpenInvalidRetryResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
		Connect: func(ctx context.Context, lastEventID string) (*http.Response, error) {
			return client.invalidRetryConnect(ctx, lastEventID, options)
		},
	}, nil)
	if err != nil {
		return SseProtocolClientOpenInvalidRetryResponse{}, err
	}
	return SseProtocolClientOpenInvalidRetryResponse{Stream: reader}, nil
}

// invalidRetryConnect opens a connection for the InvalidRetry stream.
func (client *SseProtocolClient) invalidRetryConnect(ctx context.Context, lastEventID string, options *SseProtocolClientOpenInvalidRetryOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolClient.InvalidRetry")
	req, err := client.invalidRetryCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// invalidRetryCreateRequest creates the InvalidRetry request.
func (client *SseProtocolClient) invalidRetryCreateRequest(ctx context.Context, _ *SseProtocolClientOpenInvalidRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/invalid-retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenReconnect opens the Reconnect Server-Sent Events stream. The initial
// connection is established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientReconnectOptions contains the optional parameters for the SseProtocolClient.Reconnect method.
func (client *SseProtocolClient) OpenReconnect(ctx context.Context, options *SseProtocolClientOpenReconnectOptions) (SseProtocolClientOpenReconnectResponse, error) {
	resp, err := client.reconnectConnect(ctx, "", options)
	if err != nil {
		return SseProtocolClientOpenReconnectResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
		Connect: func(ctx context.Context, lastEventID string) (*http.Response, error) {
			return client.reconnectConnect(ctx, lastEventID, options)
		},
	}, nil)
	if err != nil {
		return SseProtocolClientOpenReconnectResponse{}, err
	}
	return SseProtocolClientOpenReconnectResponse{Stream: reader}, nil
}

// reconnectConnect opens a connection for the Reconnect stream.
func (client *SseProtocolClient) reconnectConnect(ctx context.Context, lastEventID string, options *SseProtocolClientOpenReconnectOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolClient.Reconnect")
	req, err := client.reconnectCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// reconnectCreateRequest creates the Reconnect request.
func (client *SseProtocolClient) reconnectCreateRequest(ctx context.Context, _ *SseProtocolClientOpenReconnectOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/reconnect"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// OpenRetry opens the Retry Server-Sent Events stream. The initial connection is
// established before returning.
//
// The provided ctx governs the lifetime of the entire stream, not just this call:
// canceling it ends the returned stream and fails in-progress reads. Call
// Stream.Close to release the stream early.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolClientRetryOptions contains the optional parameters for the SseProtocolClient.Retry method.
func (client *SseProtocolClient) OpenRetry(ctx context.Context, options *SseProtocolClientOpenRetryOptions) (SseProtocolClientOpenRetryResponse, error) {
	resp, err := client.retryConnect(ctx, "", options)
	if err != nil {
		return SseProtocolClientOpenRetryResponse{}, err
	}
	reader, err := streaming.NewEventReader(resp, streaming.EventHandler[ProtocolEvents]{
		Decode: decodeProtocolEvents,
		Connect: func(ctx context.Context, lastEventID string) (*http.Response, error) {
			return client.retryConnect(ctx, lastEventID, options)
		},
	}, nil)
	if err != nil {
		return SseProtocolClientOpenRetryResponse{}, err
	}
	return SseProtocolClientOpenRetryResponse{Stream: reader}, nil
}

// retryConnect opens a connection for the Retry stream.
func (client *SseProtocolClient) retryConnect(ctx context.Context, lastEventID string, options *SseProtocolClientOpenRetryOptions) (*http.Response, error) {
	ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolClient.Retry")
	req, err := client.retryCreateRequest(ctx, options)
	if err != nil {
		return nil, err
	}
	if lastEventID != "" {
		req.Raw().Header.Set("Last-Event-ID", lastEventID)
	}
	resp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return nil, err
	}
	if !runtime.HasStatusCode(resp, http.StatusOK) {
		return nil, runtime.NewResponseError(resp)
	}
	return resp, nil
}

// retryCreateRequest creates the Retry request.
func (client *SseProtocolClient) retryCreateRequest(ctx context.Context, _ *SseProtocolClientOpenRetryOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/retry"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
