// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
)

// SseClient - Test of server-sent events (SSE) streaming.
// Don't use this type directly, use NewSseClientWithNoCredential() instead.
type SseClient struct {
	internal *azcore.Client
	endpoint string
}

// SseClientOptions contains the optional values for creating a [SseClient].
type SseClientOptions struct {
	azcore.ClientOptions
}

// NewSseClientWithNoCredential creates a new instance of SseClient with the specified values.
//   - endpoint - Service host
//   - options - Contains optional client configuration. Pass nil to accept the default values.
func NewSseClientWithNoCredential(endpoint string, options *SseClientOptions) (*SseClient, error) {
	if options == nil {
		options = &SseClientOptions{}
	}
	cl, err := azcore.NewClient(moduleName, moduleVersion, runtime.PipelineOptions{}, &options.ClientOptions)
	if err != nil {
		return nil, err
	}
	client := &SseClient{
		endpoint: endpoint,
		internal: cl,
	}
	return client, nil
}

// NewSseNamedClient creates a new instance of [SseNamedClient].
func (client *SseClient) NewSseNamedClient() *SseNamedClient {
	return &SseNamedClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewSseProtocolClient creates a new instance of [SseProtocolClient].
func (client *SseClient) NewSseProtocolClient() *SseProtocolClient {
	return &SseProtocolClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewSseRetrieveClient creates a new instance of [SseRetrieveClient].
func (client *SseClient) NewSseRetrieveClient() *SseRetrieveClient {
	return &SseRetrieveClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}

// NewSseUnnamedClient creates a new instance of [SseUnnamedClient].
func (client *SseClient) NewSseUnnamedClient() *SseUnnamedClient {
	return &SseUnnamedClient{
		endpoint: client.endpoint,
		internal: client.internal,
	}
}
