// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"context"
	"net/http"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// SseProtocolDataClient contains the methods for the SseProtocolData group.
// Don't use this type directly, use [SseProtocolClient.NewSseProtocolDataClient] instead.
type SseProtocolDataClient struct {
	internal *azcore.Client
	endpoint string
}

// NewWithEnvelopeEventStream opens the WithEnvelope Server-Sent Events stream.
// The initial connection is established before returning.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientWithEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithEnvelope
//     method.
func (client *SseProtocolDataClient) NewWithEnvelopeEventStream(ctx context.Context, options *SseProtocolDataClientWithEnvelopeOptions) (*streaming.Event[DataEvents], error) {
	return streaming.NewEvent(ctx, streaming.EventStreamHandler[DataEvents]{
		Decode:  decodeDataEvents,
		Connect: client.withEnvelopeConnect(options),
	})
}

// withEnvelopeConnect returns the connection factory for the WithEnvelope stream.
func (client *SseProtocolDataClient) withEnvelopeConnect(options *SseProtocolDataClientWithEnvelopeOptions) func(context.Context, string) (*http.Response, error) {
	return func(ctx context.Context, lastEventID string) (*http.Response, error) {
		ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolDataClient.WithEnvelope")
		req, err := client.withEnvelopeCreateRequest(ctx, options)
		if err != nil {
			return nil, err
		}
		if lastEventID != "" {
			req.Raw().Header.Set("Last-Event-ID", lastEventID)
		}
		resp, err := client.internal.Pipeline().Do(req)
		if err != nil {
			return nil, err
		}
		if !runtime.HasStatusCode(resp, http.StatusOK) {
			return nil, runtime.NewResponseError(resp)
		}
		return resp, nil
	}
}

// withEnvelopeCreateRequest creates the WithEnvelope request.
func (client *SseProtocolDataClient) withEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientWithEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/with-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}

// NewWithoutEnvelopeEventStream opens the WithoutEnvelope Server-Sent Events stream.
// The initial connection is established before returning.
// If the operation fails it returns an *azcore.ResponseError type.
//   - options - SseProtocolDataClientWithoutEnvelopeOptions contains the optional parameters for the SseProtocolDataClient.WithoutEnvelope
//     method.
func (client *SseProtocolDataClient) NewWithoutEnvelopeEventStream(ctx context.Context, options *SseProtocolDataClientWithoutEnvelopeOptions) (*streaming.Event[DataEvents], error) {
	return streaming.NewEvent(ctx, streaming.EventStreamHandler[DataEvents]{
		Decode:  decodeDataEvents,
		Connect: client.withoutEnvelopeConnect(options),
	})
}

// withoutEnvelopeConnect returns the connection factory for the WithoutEnvelope stream.
func (client *SseProtocolDataClient) withoutEnvelopeConnect(options *SseProtocolDataClientWithoutEnvelopeOptions) func(context.Context, string) (*http.Response, error) {
	return func(ctx context.Context, lastEventID string) (*http.Response, error) {
		ctx = context.WithValue(ctx, runtime.CtxAPINameKey{}, "SseProtocolDataClient.WithoutEnvelope")
		req, err := client.withoutEnvelopeCreateRequest(ctx, options)
		if err != nil {
			return nil, err
		}
		if lastEventID != "" {
			req.Raw().Header.Set("Last-Event-ID", lastEventID)
		}
		resp, err := client.internal.Pipeline().Do(req)
		if err != nil {
			return nil, err
		}
		if !runtime.HasStatusCode(resp, http.StatusOK) {
			return nil, runtime.NewResponseError(resp)
		}
		return resp, nil
	}
}

// withoutEnvelopeCreateRequest creates the WithoutEnvelope request.
func (client *SseProtocolDataClient) withoutEnvelopeCreateRequest(ctx context.Context, _ *SseProtocolDataClientWithoutEnvelopeOptions) (*policy.Request, error) {
	urlPath := "/streaming/sse/protocol/data/without-envelope"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	runtime.SkipBodyDownload(req)
	req.Raw().Header["Accept"] = []string{"text/event-stream"}
	return req, nil
}
