// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"encoding/json"
	"fmt"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/streaming"
)

// decodeDataEvents maps an SSE event to a DataEvents value, discriminating on the event name.
func decodeDataEvents(frame streaming.EventFrame) (DataEvents, bool, error) {
	switch frame.Type {
	case "withEnvelope":
		// @data on a text/plain property: the SSE data field is the raw contents.
		s := string(frame.Data)
		return DataEvents{WithEnvelope: &WithEnvelope{Contents: &s}}, false, nil
	case "withoutEnvelope":
		var v WithEnvelope1
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return DataEvents{}, false, err
		}
		return DataEvents{WithEnvelope1: &v}, false, nil
	default:
		return DataEvents{}, false, fmt.Errorf("unknown SSE event %q", frame.Type)
	}
}

// decodeProtocolEvents maps an SSE event to a ProtocolEvents value. Envelope
// metadata (such as the event id) is surfaced by the streaming.EventReader, not the typed payload.
func decodeProtocolEvents(frame streaming.EventFrame) (ProtocolEvents, bool, error) {
	switch frame.Type {
	case "", "message":
		var v ProtocolInfo
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return ProtocolEvents{}, false, err
		}
		return ProtocolEvents{ProtocolInfo: &v}, false, nil
	default:
		return ProtocolEvents{}, false, fmt.Errorf("unknown SSE event %q", frame.Type)
	}
}

// decodeResponseEvents maps an SSE event to a ResponseEvents value. The terminal
// "[DONE]" event ends the stream.
func decodeResponseEvents(frame streaming.EventFrame) (ResponseEvents, bool, error) {
	switch frame.Type {
	case "responseCreated":
		var v ResponseCreated
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return ResponseEvents{}, false, err
		}
		return ResponseEvents{ResponseCreated: &v}, false, nil
	case "responseDelta":
		var v ResponseDelta
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return ResponseEvents{}, false, err
		}
		return ResponseEvents{ResponseDelta: &v}, false, nil
	default:
		if s := string(frame.Data); s == "[DONE]" {
			return ResponseEvents{LiteralString: &s}, true, nil
		}
		return ResponseEvents{}, false, fmt.Errorf("unknown SSE event %q", frame.Type)
	}
}

// decodeRetrievalEvents maps an SSE event to a RetrievalEvents value. The terminal
// "[DONE]" event ends the stream.
func decodeRetrievalEvents(frame streaming.EventFrame) (RetrievalEvents, bool, error) {
	switch frame.Type {
	case "partialResult":
		var v PartialResult
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return RetrievalEvents{}, false, err
		}
		return RetrievalEvents{PartialResult: &v}, false, nil
	case "finalResult":
		var v FinalResult
		if err := json.Unmarshal(frame.Data, &v); err != nil {
			return RetrievalEvents{}, false, err
		}
		return RetrievalEvents{FinalResult: &v}, false, nil
	default:
		if s := string(frame.Data); s == "[DONE]" {
			return RetrievalEvents{LiteralString: &s}, true, nil
		}
		return RetrievalEvents{}, false, fmt.Errorf("unknown SSE event %q", frame.Type)
	}
}

// decodeUnnamedEvents maps an SSE event to an UnnamedEvents value.
func decodeUnnamedEvents(frame streaming.EventFrame) (UnnamedEvents, bool, error) {
	var v Info
	if err := json.Unmarshal(frame.Data, &v); err != nil {
		return UnnamedEvents{}, false, err
	}
	return UnnamedEvents{Info: &v}, false, nil
}
