// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

import (
	"encoding/json"
	"errors"
	"fmt"
)

func (d DataEvents) MarshalJSON() ([]byte, error) {
	var val any
	set := 0
	if d.WithEnvelope != nil {
		val = d.WithEnvelope
		set++
	}
	if d.WithEnvelope1 != nil {
		val = d.WithEnvelope1
		set++
	}
	switch set {
	case 0:
		return nil, fmt.Errorf("%T has no value", d)
	case 1:
		return json.Marshal(val)
	default:
		return nil, fmt.Errorf("set only one field in %T", d)
	}
}

func (d *DataEvents) UnmarshalJSON(data []byte) (err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("unmarshalling type %T: %s", d, err.Error())
		}
	}()
	var rawMsg map[string]json.RawMessage
	if err = json.Unmarshal(data, &rawMsg); err != nil {
		return
	}
	if hasRequiredFields(rawMsg, "contents", "metadata") {
		err = json.Unmarshal(data, &d.WithEnvelope1)
	} else if hasRequiredFields(rawMsg, "contents") {
		err = json.Unmarshal(data, &d.WithEnvelope)
	} else {
		err = errors.New("could not determine variant")
	}
	return
}

func (p ProtocolEvents) MarshalJSON() ([]byte, error) {
	var val any
	set := 0
	if p.ProtocolInfo != nil {
		val = p.ProtocolInfo
		set++
	}
	switch set {
	case 0:
		return nil, fmt.Errorf("%T has no value", p)
	case 1:
		return json.Marshal(val)
	default:
		return nil, fmt.Errorf("set only one field in %T", p)
	}
}

func (p *ProtocolEvents) UnmarshalJSON(data []byte) (err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("unmarshalling type %T: %s", p, err.Error())
		}
	}()
	var rawMsg map[string]json.RawMessage
	if err = json.Unmarshal(data, &rawMsg); err != nil {
		return
	}
	if hasRequiredFields(rawMsg, "message") {
		err = json.Unmarshal(data, &p.ProtocolInfo)
	} else {
		err = errors.New("could not determine variant")
	}
	return
}

func (r ResponseEvents) MarshalJSON() ([]byte, error) {
	var val any
	set := 0
	if r.LiteralString != nil {
		val = r.LiteralString
		set++
	}
	if r.ResponseCreated != nil {
		val = r.ResponseCreated
		set++
	}
	if r.ResponseDelta != nil {
		val = r.ResponseDelta
		set++
	}
	switch set {
	case 0:
		return nil, fmt.Errorf("%T has no value", r)
	case 1:
		return json.Marshal(val)
	default:
		return nil, fmt.Errorf("set only one field in %T", r)
	}
}

func (r *ResponseEvents) UnmarshalJSON(data []byte) (err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("unmarshalling type %T: %s", r, err.Error())
		}
	}()
	switch probeJSONKind(data) {
	case jsonObject:
		var rawMsg map[string]json.RawMessage
		if err = json.Unmarshal(data, &rawMsg); err != nil {
			return
		}
		if hasRequiredFields(rawMsg, "id") {
			err = json.Unmarshal(data, &r.ResponseCreated)
		} else if hasRequiredFields(rawMsg, "delta") {
			err = json.Unmarshal(data, &r.ResponseDelta)
		} else {
			err = errors.New("could not determine variant")
		}
	case jsonString:
		err = json.Unmarshal(data, &r.LiteralString)
	case jsonEmpty:
		err = errors.New("unexpected end of JSON input")
	case jsonNull:
		err = nil
	default:
		err = errors.New("unexpected JSON token")
	}
	return
}

func (r RetrievalEvents) MarshalJSON() ([]byte, error) {
	var val any
	set := 0
	if r.FinalResult != nil {
		val = r.FinalResult
		set++
	}
	if r.LiteralString != nil {
		val = r.LiteralString
		set++
	}
	if r.PartialResult != nil {
		val = r.PartialResult
		set++
	}
	switch set {
	case 0:
		return nil, fmt.Errorf("%T has no value", r)
	case 1:
		return json.Marshal(val)
	default:
		return nil, fmt.Errorf("set only one field in %T", r)
	}
}

func (r *RetrievalEvents) UnmarshalJSON(data []byte) (err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("unmarshalling type %T: %s", r, err.Error())
		}
	}()
	switch probeJSONKind(data) {
	case jsonObject:
		var rawMsg map[string]json.RawMessage
		if err = json.Unmarshal(data, &rawMsg); err != nil {
			return
		}
		if hasRequiredFields(rawMsg, "references") {
			err = json.Unmarshal(data, &r.FinalResult)
		} else if hasRequiredFields(rawMsg, "text") {
			err = json.Unmarshal(data, &r.PartialResult)
		} else {
			err = errors.New("could not determine variant")
		}
	case jsonString:
		err = json.Unmarshal(data, &r.LiteralString)
	case jsonEmpty:
		err = errors.New("unexpected end of JSON input")
	case jsonNull:
		err = nil
	default:
		err = errors.New("unexpected JSON token")
	}
	return
}

func (u UnnamedEvents) MarshalJSON() ([]byte, error) {
	var val any
	set := 0
	if u.Info != nil {
		val = u.Info
		set++
	}
	switch set {
	case 0:
		return nil, fmt.Errorf("%T has no value", u)
	case 1:
		return json.Marshal(val)
	default:
		return nil, fmt.Errorf("set only one field in %T", u)
	}
}

func (u *UnnamedEvents) UnmarshalJSON(data []byte) (err error) {
	defer func() {
		if err != nil {
			err = fmt.Errorf("unmarshalling type %T: %s", u, err.Error())
		}
	}()
	var rawMsg map[string]json.RawMessage
	if err = json.Unmarshal(data, &rawMsg); err != nil {
		return
	}
	if hasRequiredFields(rawMsg, "desc") {
		err = json.Unmarshal(data, &u.Info)
	} else {
		err = errors.New("could not determine variant")
	}
	return
}

type jsonKind int

const (
	jsonUnknown jsonKind = iota
	jsonObject
	jsonArray
	jsonString
	jsonNumber
	jsonBool
	jsonNull
	jsonEmpty
)

func probeJSONKind(data []byte) jsonKind {
	if len(data) == 0 {
		return jsonEmpty
	}
	for _, b := range data {
		switch b {
		case ' ', '\t', '\r', '\n':
			continue
		case '{':
			return jsonObject
		case '[':
			return jsonArray
		case '"':
			return jsonString
		case 't', 'f':
			return jsonBool
		case 'n':
			return jsonNull
		default:
			return jsonNumber
		}
	}
	return jsonUnknown
}

func hasRequiredFields(rawMsg map[string]json.RawMessage, fields ...string) bool {
	for _, field := range fields {
		if _, ok := rawMsg[field]; !ok {
			return false
		}
	}
	return len(fields) > 0
}

// decodeDataEvents maps an SSE event to a DataEvents value, discriminating on the event name.
func decodeDataEvents(evt Event) (DataEvents, bool, error) {
	switch evt.Type {
	case "withEnvelope":
		// @data on a text/plain property: the SSE data field is the raw contents.
		s := string(evt.Data)
		return DataEvents{WithEnvelope: &WithEnvelope{Contents: &s}}, false, nil
	case "withoutEnvelope":
		var v WithEnvelope1
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return DataEvents{}, false, err
		}
		return DataEvents{WithEnvelope1: &v}, false, nil
	default:
		return DataEvents{}, false, fmt.Errorf("unknown SSE event %q", evt.Type)
	}
}

// decodeProtocolEvents maps an SSE event to a ProtocolEvents value. Envelope
// metadata (id, retry) is surfaced by the EventStream, not the typed payload.
func decodeProtocolEvents(evt Event) (ProtocolEvents, bool, error) {
	switch evt.Type {
	case "", "message":
		var v ProtocolInfo
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return ProtocolEvents{}, false, err
		}
		return ProtocolEvents{ProtocolInfo: &v}, false, nil
	default:
		return ProtocolEvents{}, false, fmt.Errorf("unknown SSE event %q", evt.Type)
	}
}

// decodeResponseEvents maps an SSE event to a ResponseEvents value. The terminal
// "[DONE]" event ends the stream.
func decodeResponseEvents(evt Event) (ResponseEvents, bool, error) {
	switch evt.Type {
	case "responseCreated":
		var v ResponseCreated
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return ResponseEvents{}, false, err
		}
		return ResponseEvents{ResponseCreated: &v}, false, nil
	case "responseDelta":
		var v ResponseDelta
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return ResponseEvents{}, false, err
		}
		return ResponseEvents{ResponseDelta: &v}, false, nil
	default:
		if s := string(evt.Data); s == "[DONE]" {
			return ResponseEvents{LiteralString: &s}, true, nil
		}
		return ResponseEvents{}, false, fmt.Errorf("unknown SSE event %q", evt.Type)
	}
}

// decodeRetrievalEvents maps an SSE event to a RetrievalEvents value. The terminal
// "[DONE]" event ends the stream.
func decodeRetrievalEvents(evt Event) (RetrievalEvents, bool, error) {
	switch evt.Type {
	case "partialResult":
		var v PartialResult
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return RetrievalEvents{}, false, err
		}
		return RetrievalEvents{PartialResult: &v}, false, nil
	case "finalResult":
		var v FinalResult
		if err := json.Unmarshal(evt.Data, &v); err != nil {
			return RetrievalEvents{}, false, err
		}
		return RetrievalEvents{FinalResult: &v}, false, nil
	default:
		if s := string(evt.Data); s == "[DONE]" {
			return RetrievalEvents{LiteralString: &s}, true, nil
		}
		return RetrievalEvents{}, false, fmt.Errorf("unknown SSE event %q", evt.Type)
	}
}

// decodeUnnamedEvents maps an SSE event to an UnnamedEvents value.
func decodeUnnamedEvents(evt Event) (UnnamedEvents, bool, error) {
	var v Info
	if err := json.Unmarshal(evt.Data, &v); err != nil {
		return UnnamedEvents{}, false, err
	}
	return UnnamedEvents{Info: &v}, false, nil
}

// encodeDataEvents renders a DataEvents value to an SSE frame.
func encodeDataEvents(e DataEvents) (Event, error) {
	switch {
	case e.WithEnvelope != nil:
		var contents string
		if e.WithEnvelope.Contents != nil {
			contents = *e.WithEnvelope.Contents
		}
		return Event{Type: "withEnvelope", Data: []byte(contents)}, nil
	case e.WithEnvelope1 != nil:
		data, err := json.Marshal(e.WithEnvelope1)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "withoutEnvelope", Data: data}, nil
	default:
		return Event{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeProtocolEvents renders a ProtocolEvents value to an SSE frame.
func encodeProtocolEvents(e ProtocolEvents) (Event, error) {
	if e.ProtocolInfo != nil {
		data, err := json.Marshal(e.ProtocolInfo)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "message", Data: data}, nil
	}
	return Event{}, fmt.Errorf("no field set in %T", e)
}

// encodeResponseEvents renders a ResponseEvents value to an SSE frame.
func encodeResponseEvents(e ResponseEvents) (Event, error) {
	switch {
	case e.ResponseCreated != nil:
		data, err := json.Marshal(e.ResponseCreated)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "responseCreated", Data: data}, nil
	case e.ResponseDelta != nil:
		data, err := json.Marshal(e.ResponseDelta)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "responseDelta", Data: data}, nil
	case e.LiteralString != nil:
		return Event{Data: []byte(*e.LiteralString)}, nil
	default:
		return Event{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeRetrievalEvents renders a RetrievalEvents value to an SSE frame.
func encodeRetrievalEvents(e RetrievalEvents) (Event, error) {
	switch {
	case e.PartialResult != nil:
		data, err := json.Marshal(e.PartialResult)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "partialResult", Data: data}, nil
	case e.FinalResult != nil:
		data, err := json.Marshal(e.FinalResult)
		if err != nil {
			return Event{}, err
		}
		return Event{Type: "finalResult", Data: data}, nil
	case e.LiteralString != nil:
		return Event{Data: []byte(*e.LiteralString)}, nil
	default:
		return Event{}, fmt.Errorf("no field set in %T", e)
	}
}

// encodeUnnamedEvents renders an UnnamedEvents value to an SSE frame.
func encodeUnnamedEvents(e UnnamedEvents) (Event, error) {
	if e.Info != nil {
		data, err := json.Marshal(e.Info)
		if err != nil {
			return Event{}, err
		}
		return Event{Data: data}, nil
	}
	return Event{}, fmt.Errorf("no field set in %T", e)
}

// NewDataEventsStream builds a producer SSE stream of DataEvents for fake servers.
func NewDataEventsStream(events []DataEvents) (*EventStream[DataEvents], error) {
	return newEventStreamFromEvents(events, encodeDataEvents)
}

// NewProtocolEventsStream builds a producer SSE stream of ProtocolEvents for fake servers.
func NewProtocolEventsStream(events []ProtocolEvents) (*EventStream[ProtocolEvents], error) {
	return newEventStreamFromEvents(events, encodeProtocolEvents)
}

// NewResponseEventsStream builds a producer SSE stream of ResponseEvents for fake servers.
func NewResponseEventsStream(events []ResponseEvents) (*EventStream[ResponseEvents], error) {
	return newEventStreamFromEvents(events, encodeResponseEvents)
}

// NewRetrievalEventsStream builds a producer SSE stream of RetrievalEvents for fake servers.
func NewRetrievalEventsStream(events []RetrievalEvents) (*EventStream[RetrievalEvents], error) {
	return newEventStreamFromEvents(events, encodeRetrievalEvents)
}

// NewUnnamedEventsStream builds a producer SSE stream of UnnamedEvents for fake servers.
func NewUnnamedEventsStream(events []UnnamedEvents) (*EventStream[UnnamedEvents], error) {
	return newEventStreamFromEvents(events, encodeUnnamedEvents)
}
