// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See License.txt in the project root for license information.
// Code generated by Microsoft (R) Go Code Generator. DO NOT EDIT.

package ssegroup

type DataEvents struct {
	WithEnvelope  *WithEnvelope
	WithEnvelope1 *WithEnvelope1
}

type ProtocolEvents struct {
	ProtocolInfo *ProtocolInfo
}

type ResponseEvents struct {
	LiteralString   *string
	ResponseCreated *ResponseCreated
	ResponseDelta   *ResponseDelta
}

type RetrievalEvents struct {
	FinalResult   *FinalResult
	LiteralString *string
	PartialResult *PartialResult
}

type UnnamedEvents struct {
	Info *Info
}
